### ISSUE TITLE
Host UI and connect to assets on devnet

### ISSUE THREAD

**Issue by katelynsills** [Agoric/dapp-card-store#10]
see https://github.com/Agoric/dapp-token-economy/issues/134

**Comment by dckc** [comment]
To get started, the `ui/public/` directory is deployed at https://agoric-dapp-card-store.netlify.app/
Build started at 12:56:27 PM and ended at 12:56:31 PM.

I originally tried the default `yarn build` build script on agoric, but that failed with:
```
12:55:17 PM: please use: agoric install . For details, see https://agoric.com/documentation/
```

`agoric install` doesn't seem relevant, so I just took out the build command.

 - [ ] back end: The page says "API server: Unknown". Do you want the API hosted, @katelynsills ? A little searching didn't turn up an issue to make it back-end-less, but perhaps I'm not looking in the right place?
 - [ ] agoric.app cname: @michaelfig do you want to issue `dapp-card-store.agoric.app` or grant me authority to do it?
   - [ ] Have we decided on `dapp-card-store.agoric.app`? Should I ask @dtribble ?

**Comment by katelynsills** [comment]
I think it needs `agoric install` so that it gets the agoric-sdk packages directly and not from npm. 

I think this will need to be backend-less. I think there's an issue about doing this for all dapps, but I created a new issue for dapp-card-store specifically: https://github.com/Agoric/dapp-card-store/issues/11 This will need to do what https://github.com/Agoric/dapp-token-economy/pull/146 did.

**Comment by dckc** [comment]
In #12 I got a github action to
 1. clone, install, and build `agoric-sdk`
 2. checkout this dapp, `agoric install`
 3. `yarn build` to generate `ui/dist/`
 4. publish `ui/dist/` via netlify to https://card-store.agoric.app/
     - using netlify API keys provided to the github action via secrets in this repo's settings

Between 3 and 4, I think the `contract/deploy.js` and `api/deploy.js` scripts need to run.

They depend on an `ag-solo` though, right? I'm a little fuzzy on how to connect that to devnet, but I suppose the docs and `Makefile` in `cosmic-swingset` have the relevant clues (scenario 3?).

But what about a key pair? Is it OK to just generate a new one for each deploy? Or do we need to persist a key as a repo secret or some such?

**Comment by dckc** [comment]
https://treasury.agoric.app/ and https://card-store.agoric.app/ are live.

**Comment by dckc** [comment]
@erights tried the card store and got the following. I get the same thing.

It says "Wallet Connected" but I don't have a wallet running.

Perhaps this is a known issue, but until I find that issue number, I'll just re-open this one.

![paste](https://user-images.githubusercontent.com/150986/115470302-b5916500-a1fb-11eb-8de2-c23c9a64e36c.png)
