### ISSUE TITLE
Error running test code - "Cannot find module  /agoric-sdk/packages/SwingSet/node_modules/@endo/init/pre-bundle-source.js' imported from /Users/tg/agoric-sdk/packages/SwingSet/tools/prepare-test-env-ava.js"

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/dapp-card-store#53]
Ran into an issue a moment ago when trying to run some test code from within the dapp-card-store template. The error is as followed:

```sh

  Error: Cannot find module '/Users/tg/agoric-sdk/packages/SwingSet/node_modules/@endo/init/pre-bundle-source.js' imported from /Users/tg/agoric-sdk/packages/SwingSet/tools/prepare-test-env-ava.js
  Did you mean to import @endo/init/pre-bundle-source.js?
```

Below is the entire stack stack resulting from running `yarn run test`
```sh
❯ yarn run test
yarn run v1.22.5
$ yarn workspaces run test

> dapp-card-store-api
$ exit 0

> dapp-card-store-contract
$ ava --verbose

  Uncaught exception in test/test-contract.js

  Error: Cannot find module '/Users/tg/agoric-sdk/packages/SwingSet/node_modules/@endo/init/pre-bundle-source.js' imported from /Users/tg/agoric-sdk/packages/SwingSet/tools/prepare-test-env-ava.js
  Did you mean to import @endo/init/pre-bundle-source.js?

 1 uncaught exception
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

Initially this arose from within a directory that I had been previously working in, so I attempted to initialize a fresh instance of dapp-card-store via `agoric init` only to arrive at the same result.

**Comment by tgrecojs** [comment]
Iit seems like installing Python@2.7.x  and setting that as my default Python version allowed me to resolve the issue, which seems to have been related to the node-gyp & node-lmdb packages. 🤔 

A bit odd seeing as everything worked properly just yesterday, prior to having python@2.7 set up on my machine 🤷‍♂️. Issue is free to close but going to keep open in the event that it's relevant to behavior other users of the sdk experience.

**Comment by Tartuffo** [comment]
Closing, will be in our GH history should we encounter this again.
